### ISSUE TITLE
Its instance type 'ReactGrid' is not a valid JSX element.

### ISSUE THREAD

**Issue by nirmaanlabs** [silevis/reactgrid#107]
**Describe the bug**

```
'ReactGrid' cannot be used as a JSX component.
  Its instance type 'ReactGrid' is not a valid JSX element.
    Type 'ReactGrid' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refs
    45 |   const columns = getColumns();
    46 |
  > 47 |   return <ReactGrid rows={rows} columns={columns} />;
       |           ^^^^^^^^^
    48 | }
    49 |
```

![image](https://user-images.githubusercontent.com/102367759/175966192-28dc11ba-98dd-4a00-be25-235f5b6d9e95.png)

I copy pasted code from getting started 
using react 18.2.0
 - Device:  desktop
 - OS: Windows
 - Browser: chrome

**Comment by SimantoR** [comment]
This is due to the fact that `ReactGrid` is written as class components and I think `react@18` depricates class components. I do want to start a PR to convert it into functional components. There seems to be other depricated depenencies as well that would either need to be updated or removed all together. Looking for advice from maintainer. This is a very useful tool and I'd like to get a PR started with some guidance.

**Comment by czerwiukk** [comment]
Hello guys! The ReactGrid's codebase is quite old. There are classes like `PointerEventsController` that should be completely rewritten to hooks to apply such logic in functional components.
Currently we are working on a new version of ReactGrid from scratch, using relevant syntax and practices. We've got limited resources for that project, but we strive to announce it as soon as it's possible.

**Comment by MarcoDeJong** [comment]
If you want collaborators for that work, it might be usefull to push this to a development branch

**Comment by ChristoRibeiro** [comment]
@czerwiukk are you looking for contributors? Is the new version available somewhere?

**Comment by DLowHP** [comment]
Hi! When it comes to the mentioned issue I believe it should work now after updating `react-scripts` (see [PR#193](https://github.com/silevis/reactgrid/pull/193)).

As for questions about new version - we had to postpone this because many people are still using the current version so we need to address current issues first before introducing breaking changes and a whole new architecture. When the time comes you’ll most likely see our work in on a separate branch or somewhere 😄

Thanks for sharing your thoughts. Take care!
