### ISSUE TITLE
new ReactGrid version from the ground

### ISSUE THREAD

**Issue by imkitukov** [silevis/reactgrid#161]
**My question is where we can follow the progress of the new ReactGrid version from the ground?** 

As from other issues and discussions here, I saw that new version is planned:

"We're currently building the next version of ReactGrid from the ground up and decided to leave this topic in the current state. If you want to use the current version, disable the strict mode while using React 18."
[https://github.com/silevis/reactgrid/issues/87]

![image](https://user-images.githubusercontent.com/44986252/230610566-51e51407-04ea-4576-a8d1-35f5c9443a66.png)

**Comment by simonesanna1983** [comment]
Hello guys,

I got the same error described here https://github.com/silevis/reactgrid/issues/87.
Is there any news about the new version of ReactGrid?
I have to decide whether to adopt it in my company but for now I'm a little afraid that the last official release was on February 25th 2021. 
Thanks in advance.

**Comment by simonesanna1983** [comment]
Is there anyone over there?

> Hello guys,
> 
> I got the same error described here #87. Is there any news about the new version of ReactGrid? I have to decide whether to adopt it in my company but for now I'm a little afraid that the last official release was on February 25th 2021. Thanks in advance.

**Comment by alonshmiel** [comment]
Hi,
I know a lot of developers were waiting for upgrading this amazing library to React 18.

So I have good news!!
I forked this library to my account and made the relevant changes in order to make it work in React 18.
I have tested it on my Mac but please test it also and verify everything works.

I updated React to 18, node-sass to sass and changed the config of rollup to use sass instead of node-sass.
So I succeeded to use this library with strict mode:

```
<React.StrictMode>
      <Grid...../>
</React.StrictMode>
```

I will make a PR for this library so the maintainers will be able to merge it to their library.

You can install my library by:

`npm install git+https://github.com/alonshmiel/reactgrid.git`

And then you can use the CSS by:

`@import "@silevis/reactgrid/dist/styles.scss";
`
And the JS by:
```
import {
  ReactGrid,
  getCellProperty,
  getCharFromKeyCode,
  inNumericKey,
  isAllowedOnNumberTypingKey,
  isAlphaNumericKey,
  isNavigationKey,
  isNumpadNumericKey,
  keyCodes,
} from "@silevis/reactgrid/dist/core";
```

I faced with an error when using strict mode (can't access property "scrollableElement", t is undefined)
It was because of the strict mode.
React StrictMode calls reducer two times to eliminate any side-effects.
This error was thrown because the reducer didn't store the state so the second call didn't have the old state that it needs. That's why I stored the state.

Please open any issue you face with,
and I hope to maintain this library as much as I can since I'm gonna have a new baby boy in my family 💚

**Comment by alonshmiel** [comment]
Hi @fellmann , you can close this issue.

@simonesanna1983 , @imkitukov ,
A new version was deployed (4.0.5) that uses React 18.
Thanks!

**Comment by fellmann** [comment]
Duplicated by https://github.com/silevis/reactgrid/issues/169
