### ISSUE TITLE
Will the CellTemplate work with AutocompleteInput for MUI [Need Help]

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#186]
I am trying to make a free solo cell template.
[codesandbox](https://codesandbox.io/p/sandbox/magical-wildflower-c3m5s4?file=%2Fsrc%2FApp.tsx%3A61%2C9-61%2C15)

The problem is that, whenever I click on dropdown values the onChange is not getting called.

**Comment by alonshmiel** [comment]
Hi,
There are another issues before I can take a look.
1. The x button of the dropdown throws an error (length of undefined)
2. If you try to delete the input and then press on the input again, an error is thrown. (toLowerCase of undefined).

Can you please fix it?

**Comment by DVGY** [comment]
Hello

I have fixed both [codesandbox](https://codesandbox.io/p/sandbox/magical-wildflower-c3m5s4?file=%2Fsrc%2FApp.tsx%3A61%2C9-61%2C15)

**Comment by DVGY** [comment]
Update: If you try to select option with down arrow keys and press enter, it seems to be working

**Comment by alonshmiel** [comment]
Interesting.
I am not sure that the onChange of autocomplete is called.
Can you please try to move the autocomplete component out of the grid and make sure onChange is called?

Please let me know..

**Comment by DVGY** [comment]
Seems to be working I just added it outside the grid
[codesandbox](https://codesandbox.io/p/sandbox/magical-wildflower-c3m5s4?file=%2Fsrc%2FApp.tsx%3A163%2C41)

**Comment by pawaningale93** [comment]
on change method is not calling when we are selecting the option while if we type and select from keyboard then it is working fine.

**Comment by DVGY** [comment]
@pawaningale93 I switched to a different library, and it is working fine.

**Comment by pawaningale93** [comment]
If possible, can you please suggest which library you moved to?.

**Comment by DVGY** [comment]
> If possible, can you please suggest which library you moved to?.

https://github.com/adazzle/react-data-grid this one

**Comment by pawaningale93** [comment]
Thanks :)

**Comment by DLowHP** [comment]
Hi! I took a look at Material UI Autocomplete input and put together a [POC sandbox](https://codesandbox.io/s/reactgrid-muiautocomplete-cell-5p5563) with core ReactGrid functionalities (such as copy/cut/paste, fill and clear) implemented. There are still some problems with the MUI component itself (or at least I believe they are not caused by ReactGrid), but other than that everything seems to be fine. It's certainly doable, although it requires some time and experience with both libraries. I'm not an expert when it comes to MUI, so some things can be done better, but unfortunately I don't have more time for that right now. Nevertheless, I hope this will at least point you in the right direction and help you implement it correctly.

**Comment by DVGY** [comment]
@DLowHP thanks for putting that out. Whether the problem is in MUI or ReactGrid is still a mystery. I was short on time so I switched to different library

**Comment by DLowHP** [comment]
Oh, that's understandable. I'll close this issue but I invite you to check out our upcoming v5 version when it comes out 😄 Please keep your fingers closed so that I can fruitfully work on it and we could release it soon 🤞🏻🚀
