### ISSUE TITLE
onSelectionChanged behaves differently when selecting with Shift/Command

### ISSUE THREAD

**Issue by mathdevelop** [silevis/reactgrid#248]
When we select using Shift, we receive a single array in the onSelectionChanged/onSelectionChanging callback, containing the selected columns/rows. Now, if I select using Command (on Mac) / Ctrl (on Windows), for each cell, it's a separate item in the array containing only its column/row; Another aspect of using Command is that with it, you can deselect cell by cell, whereas with Shift, it deselects the entire row/column. Personally, I prefer the behavior of Command because it's easier to control and know exactly which cell is being selected at that moment, without depending on a separate state, etc. The problem with having two behaviors is that each user will select with a different key unless we can block one, for example, the Shift key.

Code:
```
const handleSelectionChanged = (selectedRanges: any) => {
  console.log('handleSelectionChanged')
  console.log(selectedRanges)
}

const handleSelectionChanging = (selectedRanges: any): boolean => {
  console.log('handleSelectionChanging')
  console.log(selectedRanges)
}


<ReactGrid
  ...
  onSelectionChanged={handleSelectionChanging}
  onSelectionChanging={handleSelectionChanging}
  enableRangeSelection
/>
```

**Comment by DLowHP** [comment]
Well, that's because these functions return selected *range**s***, plural. While selecting with shift you only get one range but when you hold ctrl/cmd and use a pointer you may get multiple ranges containing single or multiple cells in different places. I don't see how this could be improved while keeping the distinction between selection types?
