### ISSUE TITLE
Editable Cell Appearing Away from Original Cell Position when rendering ReactGrid in a dialog

### ISSUE THREAD

**Issue by bobbyflowstate** [silevis/reactgrid#255]
**Describe the bug**
Editable Cell Appearing Away from Original Cell Position when rendering ReactGrid in a dialog. 

**Current behavior**
Editable Cell Appearing Away from Original Cell Position when rendering ReactGrid in a dialog

**Expected behavior**
The Editable Cell should appear right above the original cell position.

**Screenshots or gifs**

https://github.com/silevis/reactgrid/assets/2475027/be60f1dd-565a-41b2-b6fa-6e5a39551334

Is there something special I have to do to render this properly in a pop up dialog? I'm guessing the calculation ReactGrid is making is not accounting for the popup dialog position?

**Your environment details**
 - Device:  Desktop
 - OS: Mac OS
 - Browser Chrome

**Comment by DLowHP** [comment]
Does the dialog use CSS transform?

**Comment by IdoBouskila** [comment]
Can you reproduce this to [CodeSandBox](https://react.new)?

**Comment by glubb92** [comment]
I've got the same issue, but not in a dialog.

After trying to reproduce it in a CodeSandBox, I figured it has probably to do with my framer-motion animations.
https://codesandbox.io/p/sandbox/boring-haze-s27xpm

Since they are also often used in dialogs, this could be the main problem.

I reused the workhours example for the sandbox and there appear to be more issues. This is not the case in my project, where only the edited cell is misplaced, so I assume I missed something in the example.
Regardless you can clearly see, that the cell is not where it should be while editing.

In my case it is also misplaced in both dimensions, like in @rajuashok  video.

I hope this helps.

**Comment by IdoBouskila** [comment]
> I've got the same issue, but not in a dialog.
> 
> After trying to reproduce it in a CodeSandBox, I figured it has probably to do with my framer-motion animations. https://codesandbox.io/p/sandbox/boring-haze-s27xpm
> 
> Since they are also often used in dialogs, this could be the main problem.
> 
> I reused the workhours example for the sandbox and there appear to be more issues. This is not the case in my project, where only the edited cell is misplaced, so I assume I missed something in the example. Regardless you can clearly see, that the cell is not where it should be while editing.
> 
> In my case it is also misplaced in both dimensions, like in @rajuashok video.
> 
> I hope this helps.

This is because you're using the property `transform`. You should get rid of line 33 in `App.jsx` in the CSB you provided.

![image](https://github.com/silevis/reactgrid/assets/94786579/e6cfca56-c342-4470-9f08-233890103594)

**Comment by glubb92** [comment]
Hi, thank you for your quick response!

Yes if I remove all animations, it is working like expected. But in my case the table is in a box which has several animations and I can't simply remove them. The whole project uses those animations and it is kind of a core function in our app.

If I put the table in a dialog, which also has such animations, it appears to have the same issue.
I just provided a raw example with basic framer-motion animations to reproduce it. Because it is probably not related to a dialog, more to the animations.

**Comment by IdoBouskila** [comment]
> Hi, thank you for your quick response!
> 
> Yes if I remove all animations, it is working like expected. But in my case the table is in a box which has several animations and I can't simply remove them. The whole project uses those animations and it is kind of a core function in our app.
> 
> If I put the table in a dialog, which also has such animations, it appears to have the same issue. I just provided a raw example with basic framer-motion animations to reproduce it. Because it is probably not related to a dialog, more to the animations.

I understand. I don't think there is any solution on your side... :/
 just wait for `reactgrid` to able us to disable `fixed` cell.

**Comment by MichaelMatejko** [comment]
feature was moved to v5.
