### ISSUE TITLE
checkbox cannot auto-fill

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#293]
**Describe the bug**
checkbox cannot auto-fill

**Expected behavior**
Check boxes fill in automatically

**Screenshots or gifs**

![checkbox cannot auto-fill](https://github.com/silevis/reactgrid/assets/36500514/2d8cfa87-9673-48cb-9d10-c11605a7e9fc)

**Your environment details**
 - Device:  [e.g.desktop]
 - Browser [e.g. chrome]

**Comment by Michota** [comment]
Thank you for your contribution, @qiufeihong2018.
We find it helpful, especially if you attach gif like the one above. But, please, if you report an issue, and you use a issue-template, fill these fields according to what they suppose to describe, instead of simply leaving it as they are (for example: In "_Describe the bug_" tell other participants what do you actually mean by a bug).

**Comment by qiufeihong2018** [comment]
@Michota Aha, let me change the template. Originally, I felt that the simple question could be understood by seeing the title and gif, so I did not change the template

**Comment by Michota** [comment]
Close the issue @DLowHP if last commit actually patches this bug.
Thanks!

**Comment by qiufeihong2018** [comment]
fixed
