### ISSUE TITLE
The cell editor is misplaced if one of the ancestors of the component is css translated

### ISSUE THREAD

**Issue by enderortak** [silevis/reactgrid#90]
**Describe the bug**
The cell editor is misplaced if one of the ancestors of the component is css translated (transform: translate(10px, 10px))

**Current behavior**
The cell editor has a margin of x, y pixels if one of the ancestors have "transform: translate(x px, y px)" css rule.

**Expected behavior**
The cell editor is displayed where it is meant to be without any margins.

**Screenshots or gifs**
![image](https://user-images.githubusercontent.com/10289426/170007633-44ff4f26-dcc5-42fc-ab7a-1c0c5c9288f5.png)

**Your environment details**
 - Device:  Desktop
 - OS: Windows 10
 - Browser: Chrome 100.0.4896.127

**Comment by aqibasif** [comment]
Hi @enderortak,
Did you manage to resolve this issue? because I'm also facing this same issue.

**Comment by enderortak** [comment]
Hello @aqibasif,
Unfortunately I could not resolve the issue :(
Still waiting for a workaround suggestion.

**Comment by czerwiukk** [comment]
Hello, thank you for reporting the issue.
We'll investigate this bug as fast as possible.

**Comment by alonshmiel** [comment]
@enderortak , can you please send a link with an example for that?

**Comment by enderortak** [comment]
> @enderortak , can you please send a link with an example for that?

@alonshmiel  Here you go: [https://codesandbox.io/embed/serverless-silence-910069?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/embed/serverless-silence-910069?fontsize=14&hidenavigation=1&theme=dark)

**Comment by DLowHP** [comment]
Hi! I investigated the issue and I must unfortunately say this won't be fixed anytime soon because:

> Specifying a value other than none for the [transform](https://www.w3.org/TR/css-transforms-1/#propdef-transform) property establishes a new [local coordinate system](https://www.w3.org/TR/css-transforms-1/#local-coordinate-system) at the element that it is applied to. The mapping from where the element would have rendered into that local coordinate system is given by the element’s [transformation matrix](https://www.w3.org/TR/css-transforms-1/#transformation-matrix).
(see: [CSS Transform - w3.org](https://www.w3.org/TR/css-transforms-1/#transform-rendering))

and furthermore

> 4. If the position property is absolute or fixed, the containing block may also be formed by the edge of the padding box of the nearest ancestor element that has the following:
&nbsp;&nbsp;&nbsp;&nbsp;i. A [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) or [perspective](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective) value other than none
&nbsp;&nbsp;&nbsp;&nbsp;<...>

(see point 4/i: [Layout and the containing block - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block)).

For now, I strongly advise you to try using different CSS methods of positioning. At the same time if you have a specific case where you feel like using CSS transform/translate is the only suitable option feel free to text me - maybe we can solve this problem together from a different angle.

Sorry this took so long, take care!
